language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --dev
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --coverage-clover ./build/logs/clover.xml

notifications:
  email:
    - r.janot+travis-ci@gmail.com

after_success:
    - php vendor/bin/php-coveralls -v
